name: LabelTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  labeltest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: startsWith(github.ref, 'refs/tags/')
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
        if: startsWith(github.ref, 'refs/tags/')
        
      - name: Install Python packages
        run: pip install mkdocs-material mike
        if: startsWith(github.ref, 'refs/tags/')
        
      - name: Update Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ls -alh
          TAG_LATEST=$(git describe --tags --abbrev=0)
          echo "TAG='$TAG_LATEST'"
          echo "git Ref: ${{ github.ref }}"
          echo "Ref Name ${{ github.ref_name }}"
